import HackingPipelineInstance, {
  HackingPipelineResultKey,
} from "../../../domain/entities/hacking-pipeline-instance";
import { ReconResultEntity } from "../../2-recon/domain/entities";
import { ScanResultEntity } from "../../3-scan/domain/entities/scan-result.entity";
import { VulnerabilityAnalysisResult } from "../../4-vuln-analysis/domain/entities/vuln-analysis-result.entity";
import { HtmlIndexBuilder } from "./html-index.builder";
import { HtmlCoverBuilder } from "./html-cover.builder";
import { HtmlReconBuilder } from "./html-recon.builder";
import { HtmlScanBuilder } from "./html-scan.builder";
import { HtmlVulnBuilder } from "./html-vuln.builder";

export class HtmlReportOrchestrator {
  static build(instance: HackingPipelineInstance): string {
    const results = instance.results || {};

    // Debug log to trace what data is actually reaching the builder
    console.log(
      "Orchestrator Received Results:",
      JSON.stringify(results, null, 2)
    );

    const recon = results[HackingPipelineResultKey.RECON] as
      | ReconResultEntity
      | undefined;
    const scan = results[HackingPipelineResultKey.SCANNING] as
      | ScanResultEntity
      | undefined;
    const vuln = results[HackingPipelineResultKey.VULN_ANALYSIS] as
      | VulnerabilityAnalysisResult
      | undefined;

    const styles = this.getGlobalStyles();

    return `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8">
          <style>
            ${styles}
          </style>
        </head>
        <body>
          ${HtmlCoverBuilder.build(instance)}
          ${HtmlIndexBuilder.build()}
          ${HtmlReconBuilder.build(recon)}
          ${HtmlScanBuilder.build(scan)}
          ${HtmlVulnBuilder.build(vuln)}
          
          <div class="footer">
            Generated by CatchMeIfYouHack - ${new Date().toLocaleDateString()}
          </div>
        </body>
      </html>
    `;
  }

  private static getGlobalStyles(): string {
    return `
      @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700;800&family=Roboto+Mono:wght@400;500;700&family=Roboto:wght@300;400;500;700&display=swap');

      :root {
        --primary: #22c55e;       /* Your Hacker Green */
        --secondary: #15803d;     /* Darker Green */
        --bg-light: #ffffff;      /* White Background */
        --bg-card: #f8fafc;       /* Very Light Gray */
        --text-dark: #1e293b;     /* Slate 800 */
        --text-dim: #64748b;      /* Slate 500 */
        --border: #e2e8f0;        /* Slate 200 */
        --critical: #dc2626;      /* Red 600 */
        --high: #ea580c;          /* Orange 600 */
        --medium: #ca8a04;        /* Yellow 600 */
        --low: #2563eb;           /* Blue 600 */
      }

      body {
        font-family: 'Roboto', sans-serif;
        background-color: var(--bg-light);
        color: var(--text-dark);
        margin: 0;
        padding: 40px;
        line-height: 1.6;
        font-size: 14px;
        -webkit-print-color-adjust: exact;
      }

      h1, h2, h3, h4 {
        font-family: 'Roboto Mono', monospace;
        color: var(--text-dark);
        margin-top: 2em;
        margin-bottom: 1em;
        font-weight: 700;
        letter-spacing: -0.025em;
      }
      
      h1 { 
        font-size: 28px; 
        border-bottom: 3px solid var(--primary); 
        padding-bottom: 0.5em; 
        color: var(--primary);
      }
      
      h2 { 
        font-size: 20px; 
        border-bottom: 1px solid var(--border);
        padding-bottom: 0.3em;
        margin-top: 1.5em;
        color: var(--secondary);
      }
      
      h3 { font-size: 16px; color: var(--secondary); margin-bottom: 0.5em; }

      .section {
        margin-bottom: 50px;
        page-break-inside: avoid;
      }

      .card {
        background: var(--bg-card);
        border: 1px solid var(--border);
        border-radius: 4px; /* Sharper corners for tech feel */
        padding: 20px;
        margin-bottom: 20px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.05);
      }

      .grid {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 20px;
      }

      .badge {
        font-family: 'Roboto Mono', monospace;
        display: inline-block;
        padding: 4px 10px;
        border-radius: 4px;
        font-size: 11px;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 0.05em;
      }

      .badge-critical { background: #fef2f2; color: var(--critical); border: 1px solid #fee2e2; }
      .badge-high { background: #fff7ed; color: var(--high); border: 1px solid #ffedd5; }
      .badge-medium { background: #fefce8; color: var(--medium); border: 1px solid #fef9c3; }
      .badge-low { background: #eff6ff; color: var(--low); border: 1px solid #dbeafe; }

      table {
        width: 100%;
        border-collapse: separate;
        border-spacing: 0;
        margin-top: 15px;
        font-size: 13px;
        border: 1px solid var(--border);
        border-radius: 4px;
        overflow: hidden;
      }

      th, td {
        text-align: left;
        padding: 12px 16px;
        border-bottom: 1px solid var(--border);
      }

      th {
        background-color: #f0fdf4; /* Very light green */
        color: var(--secondary);
        font-family: 'Roboto Mono', monospace;
        font-weight: 600;
        text-transform: uppercase;
        font-size: 11px;
        letter-spacing: 0.05em;
        border-bottom: 2px solid var(--primary);
      }

      tr:last-child td { border-bottom: none; }
      tr:nth-child(even) { background-color: #f8fafc; }

      a { color: var(--primary); text-decoration: none; font-weight: 500; }
      a:hover { text-decoration: underline; }
      
      .footer {
        margin-top: 60px;
        text-align: center;
        font-family: 'Roboto Mono', monospace;
        font-size: 10px;
        color: var(--text-dim);
        border-top: 1px solid var(--border);
        padding-top: 30px;
      }

      .page-break { page-break-before: always; }
      
      /* Markdown content styles */
      .markdown-content h3 { color: var(--secondary); margin-top: 1.5em; font-family: 'Roboto Mono', monospace; }
      .markdown-content ul { padding-left: 20px; color: var(--text-dark); }
      .markdown-content li { margin-bottom: 8px; }
      .markdown-content strong { color: var(--secondary); font-weight: 700; }
      .markdown-content p { margin-bottom: 1em; color: var(--text-dark); }
      
      /* Tech stack items */
      li { font-family: 'Roboto Mono', monospace; font-size: 12px; }
    `;
  }
}
